name: CI

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Typecheck
              run: npm run typecheck

            - name: Unit tests
              run: npm run test:unit:ci

            - name: E2E tests (Cypress)
              uses: cypress-io/github-action@v6
              with:
                  install: false
                  build: npm run build
                  start: npm run serve
                  wait-on: "http://127.0.0.1:3000/"
                  browser: electron
